[package]
name = "pot"
version = "0.1.0"

[lib]
path = "src/lib.rs"
kind = "account-component"
namespace = "miden:pot/pot@0.1.0"

[dependencies]
miden-core = "*"
miden-protocol = "*"

[package.metadata.miden]
supported-types = ["RegularAccountImmutableCode"]
