[package]
name = "claim-note"
version = "0.1.0"

[lib]
path = "src/lib.rs"
kind = "note"
namespace = "miden:claim-note/miden-claim-note@0.1.0"

[dependencies]
miden-core = "*"
miden-protocol = "*"
pot = { path = "../pot" }
